const CompData = [
        {
            li1:"Problem",
            link1:"#problem",
            li2:"Research",
            link2:"#research",
            li3:"Goals",
            link3:"#goals",
            li4:"Personas",
            link4:"#personas",
            li5:"Proccess",
            link5:"#proccess",
            li6:"UX",
            link6:"#ux",
            li7:"Solutions",
            link7:"#solutions",
            li8:"Takeaways",
            link8:"#takeaways",
            title1:"VIRA",
            subtitle1:"Your Personal Mental Health Companion",
            subtitle2:"In an age where technology has allowed people to reach out quickly, there is little support for mental health. Research shows a 93% increase in anxiety screens and a 62% increase in depression screens from 2019. Current solutions disregard a humanized approach creating a missed opportunity to utilize the technology of today.",
            subtitle3:"What if there was an effective digital method of coping with mental health?",
            title2:"Role",
            subtitle4:"Research, UI/UX",
            subtitle5:"",
            title3:"Duration",
            subtitle6:"4 Weeks",
            subtitle7:"",
            title4:"Software",
            subtitle8:"Figma,illustrator",
            subtitle9:"",
            img1:"",
        }
    ]

    export default CompData;